import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import { Favorite, PersonPin, Phone, PhoneMissed } from "@mui/icons-material";
import { Box, Grid, Tab, Tabs } from "@mui/material";
// CUSTOM COMPONENTS
import ComponentPageLayout from "../../ComponentPageLayout";
import { Paragraph } from "@/components/typography";
import { Block } from "@/components/block";
function TabPanel({ children, value, index, ...props }) {
    return (_jsx(Box, { mt: 2, role: "tabpanel", hidden: value !== index, ...props, children: value === index && (_jsx(Box, { p: 3, boxShadow: 1, borderRadius: 2, bgcolor: ({ palette: { mode } }) => mode === "dark" ? "grey.700" : "white", children: _jsx(Paragraph, { children: children }) })) }));
}
const MuiTabsPageView = () => {
    const [value, setValue] = useState(0);
    const handleChange = (_, newValue) => setValue(newValue);
    return (_jsx(ComponentPageLayout, { title: "Tabs", children: _jsxs(Grid, { container: true, spacing: 3, children: [_jsx(Grid, { item: true, lg: 6, xs: 12, children: _jsxs(Block, { title: "Basic", children: [_jsxs(Tabs, { value: value, onChange: handleChange, children: [_jsx(Tab, { label: "Item One" }), _jsx(Tab, { label: "Item Two" }), _jsx(Tab, { label: "Item Three" })] }), _jsx(TabPanel, { value: value, index: 0, children: "Item One" }), _jsx(TabPanel, { value: value, index: 1, children: "Item Two" }), _jsx(TabPanel, { value: value, index: 2, children: "Item Three" })] }) }), _jsx(Grid, { item: true, lg: 6, xs: 12, children: _jsxs(Block, { title: "Secondary Color", children: [_jsxs(Tabs, { value: value, onChange: handleChange, textColor: "secondary", indicatorColor: "secondary", children: [_jsx(Tab, { label: "Item One" }), _jsx(Tab, { label: "Item Two" }), _jsx(Tab, { label: "Item Three" })] }), _jsx(TabPanel, { value: value, index: 0, children: "Item One" }), _jsx(TabPanel, { value: value, index: 1, children: "Item Two" }), _jsx(TabPanel, { value: value, index: 2, children: "Item Three" })] }) }), _jsx(Grid, { item: true, lg: 6, xs: 12, children: _jsx(Block, { title: "Scrollable", children: _jsxs(Tabs, { value: value, onChange: handleChange, variant: "scrollable", scrollButtons: "auto", children: [_jsx(Tab, { label: "Item One" }), _jsx(Tab, { label: "Item Two" }), _jsx(Tab, { label: "Item Three" }), _jsx(Tab, { label: "Item Four" }), _jsx(Tab, { label: "Item Five" }), _jsx(Tab, { label: "Item Six" }), _jsx(Tab, { label: "Item Seven" })] }) }) }), _jsx(Grid, { item: true, lg: 6, xs: 12, children: _jsx(Block, { title: "Icon", children: _jsxs(Tabs, { value: value, onChange: handleChange, children: [_jsx(Tab, { icon: _jsx(Phone, {}), "aria-label": "phone" }), _jsx(Tab, { icon: _jsx(Favorite, {}), "aria-label": "favorite" }), _jsx(Tab, { icon: _jsx(PersonPin, {}), "aria-label": "person" })] }) }) }), _jsx(Grid, { item: true, lg: 6, xs: 12, children: _jsx(Block, { title: "Icon With Label", children: _jsxs(Tabs, { value: value, onChange: handleChange, "aria-label": "icon label tabs example", children: [_jsx(Tab, { icon: _jsx(Phone, {}), label: "RECENT" }), _jsx(Tab, { icon: _jsx(Favorite, {}), label: "FAVORITES" }), _jsx(Tab, { icon: _jsx(PersonPin, {}), label: "NEARBY" })] }) }) }), _jsx(Grid, { item: true, lg: 6, xs: 12, children: _jsx(Block, { title: "Icon position", children: _jsxs(Tabs, { value: value, onChange: handleChange, "aria-label": "icon position tabs example", children: [_jsx(Tab, { icon: _jsx(Phone, {}), label: "TOP" }), _jsx(Tab, { icon: _jsx(PhoneMissed, {}), iconPosition: "start", label: "START" }), _jsx(Tab, { icon: _jsx(Favorite, {}), iconPosition: "end", label: "END" }), _jsx(Tab, { icon: _jsx(PersonPin, {}), iconPosition: "bottom", label: "BOTTOM" })] }) }) })] }) }));
};
export default MuiTabsPageView;
