export const formeJuridiqueMap: Record<string, string> = {
  "1000": "Entreprise individuelle",
  "1100": "Entreprise individuelle à responsabilité limitée (EIRL)",
  "1300": "Entreprise unipersonnelle à responsabilité limitée (EURL)",
  "1400": "Société en nom collectif (SNC)",
  "1500": "Société en commandite simple (SCS)",
  "1600": "Société en commandite par actions (SCA)",
  "1700": "Société en participation",
  "1800": "Société civile",
  "1900": "Société d’exercice libéral (SEL)",
  "2100": "Société anonyme (SA)",
  "2200": "Société par actions simplifiée (SAS)",
  "2300": "Société à responsabilité limitée (SARL)",
  "2400": "Société coopérative (SCOP, SCIC)",
  "2500": "Groupement d’intérêt économique (GIE)",
  "2600": "Association",
  "2700": "Fondation",
  "2800": "Commerçant non établi en France",
  "2900": "Autres formes juridiques",
  "3100": "Société européenne",
  "3200": "Société d’exercice libéral par actions simplifiée (SELAS)",
  "3300": "Société d’exercice libéral à responsabilité limitée (SELARL)",
  "3400": "Société d’exercice libéral en nom collectif (SELNC)",
  "3500": "Société d’exercice libéral en commandite simple (SELS)",
  "3600": "Société d’exercice libéral en commandite par actions (SELCA)",
  "3700": "Société d’exercice libéral en participation (SELP)",
  "3800": "Société civile professionnelle (SCP)",
  "3900": "Société civile immobilière (SCI)",
  "4000": "Société d’exercice libéral à forme coopérative",
  "4100": "Groupement d’intérêt public (GIP)",
  "4200": "Entreprise unipersonnelle à responsabilité limitée à associé unique",
  "5499": "Société à responsabilité limité"
};
